package com.example.cardgame.enums

enum class PlayingCard(val cardFamily: String,val value:Int) {
    CLUBS_2("clubs",2),
    CLUBS_3("clubs",3),
    CLUBS_4("clubs",4),
    CLUBS_5("clubs",5),
    CLUBS_6("clubs",6),
    CLUBS_7("clubs",7),
    CLUBS_8("clubs",8),
    CLUBS_9("clubs",9),
    CLUBS_10("clubs",10),
    CLUBS_JACK("clubs",11),
    CLUBS_QUEEN("clubs",12),
    CLUBS_KING("clubs",13),
    CLUBS_ACE("clubs",14),

    DIAMONDS_2("diamonds",2),
    DIAMONDS_3("diamonds",3),
    DIAMONDS_4("diamonds",4),
    DIAMONDS_5("diamonds",5),
    DIAMONDS_6("diamonds",6),
    DIAMONDS_7("diamonds",7),
    DIAMONDS_8("diamonds",8),
    DIAMONDS_9("diamonds",9),
    DIAMONDS_10("diamonds",10),
    DIAMONDS_JACK("diamonds",11),
    DIAMONDS_QUEEN("diamonds",12),
    DIAMONDS_KING("diamonds",13),
    DIAMONDS_ACE("diamonds",14),

    HEARTS_2("hearts",2),
    HEARTS_3("hearts",3),
    HEARTS_4("hearts",4),
    HEARTS_5("hearts",5),
    HEARTS_6("hearts",6),
    HEARTS_7("hearts",7),
    HEARTS_8("hearts",8),
    HEARTS_9("hearts",9),
    HEARTS_10("hearts",10),
    HEARTS_JACK("hearts",11),
    HEARTS_QUEEN("hearts",12),
    HEARTS_KING("hearts",13),
    HEARTS_ACE("hearts",14),

    SPADES_2("spades",2),
    SPADES_3("spades",3),
    SPADES_4("spades",4),
    SPADES_5("spades",5),
    SPADES_6("spades",6),
    SPADES_7("spades",7),
    SPADES_8("spades",8),
    SPADES_9("spades",9),
    SPADES_10("spades",10),
    SPADES_JACK("spades",11),
    SPADES_QUEEN("spades",12),
    SPADES_KING("spades",13),
    SPADES_ACE("spades",14),

    JOKER("multiple",15);
}