package com.example.cardgame.enums

enum class Token(strValue:String,chrValue:Char) {
    JSON_OPEN_OBJECT("JSON_OPEN_OBJECT",':'),
    JSON_OPEN_STRING("JSON_OPEN_STRING",'"'),
    JSON_OPEN_LIST("JSON_OPEN_LIST",'['),
    JSON_OPEN_DIC("JSON_OPEN_DIC",'{'),
    JSON_CLOSE_LIST("JSON_CLOSE_LIST",']'),
    JSON_CLOSE_DIC("JSON_CLOSE_DIC",'}'),
    JSON_NEW_PARAMETER("JSON_NEW_PARAMETER",','),
    JSON_NUMBER_VALUE("JSON_NUMBER_VALUE",'1'),
    JSON_STRING_VALUE("JSON_STRING_VALUE",'A'),
    JSON_BOOLEAN_VALUE("JSON_BOOLEAN_VALUE",'0'),
    JSON_TOKEN_UNKNOWN("JSON_TOKEN_UNKNOWN",'_')
}